version: '3.4'

services:
  bestinver.bbdd:
    environment:
      - SA_PASSWORD=Kabel.2020
    ports:
      - "1433"
  bestinver.gestoraltas.web.public:
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=C:\https\certs\localhost.pfx
      - LdapSettings__Servers__0__Name=kabel.int
      - LdapSettings__Servers__0__Credentials__Password=Dogfi4.sh
      - LdapSettings__Servers__0__Credentials__DistinguishedName=CN=Miguel Angel del Campo Morales,OU=Internos,OU=Usuarios,DC=kabel,DC=int
      - LdapSettings__SearchBase=OU=Internos,OU=Usuarios,DC=kabel,DC=int
      - LdapSettings__Group__SearchBase=OU=Grupos,OU=Usuarios,DC=kabel,DC=int
      - LdapSettings__DomainName=kabel
      - LdapSettings__DomainDistinguishedName=DC=kabel,DC=int
      - LdapSettings__ContainerName=OU=Internos,OU=Usuarios,DC=kabel,DC=int
      - IdentityServerSection__ClientSecret=cekAYwBlAA==des
      - IdentityServerSection__ClientId=openIdKabelMiddleoffice
      - IdentityServerSection__Authority=https://bestinver-id-dev.azurewebsites.net/
      - AppSettings__ApiWebPrivadaBaseAddress=https://bestinver-microservices-dev.azurewebsites.net/
      - ApplicationInsights__InstrumentationKey=5a7144dc-f2eb-4db8-98ed-e1dd497ff712
      - ApplicationInsights__ApplicationName=WebAltasDes
      - ConnectionStrings__BestinverSts=Data Source=bestinver.bbdd;Initial Catalog=STS1;User ID=sa;Password=Kabel.2020;

    ports:
      - "80"
      - "443"
    volumes:
      #- ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
      - ./docker/certificates:C:\https\certs
  bestinver.gestoraltas.web.management:
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=C:\https\certs\localhost.pfx
      - LdapSettings__Servers__0__Name=kabel.int
      - LdapSettings__Servers__0__Credentials__Password=Dogfi4.sh
      - LdapSettings__Servers__0__Credentials__DistinguishedName=CN=Miguel Angel del Campo Morales,OU=Internos,OU=Usuarios,DC=kabel,DC=int
      - LdapSettings__SearchBase=OU=Internos,OU=Usuarios,DC=kabel,DC=int
      - LdapSettings__Group__SearchBase=OU=Grupos,OU=Usuarios,DC=kabel,DC=int
      - LdapSettings__DomainName=kabel
      - LdapSettings__DomainDistinguishedName=DC=kabel,DC=int
      - LdapSettings__ContainerName=OU=Internos,OU=Usuarios,DC=kabel,DC=int
      - IdentityServerSection__ClientSecret=cekAYwBlAA==des
      - IdentityServerSection__ClientId=openIdKabelMiddleoffice
      - IdentityServerSection__Authority=https://bestinver-id-dev.azurewebsites.net/
      - AppSettings__ApiWebPrivadaBaseAddress=https://bestinver-microservices-dev.azurewebsites.net/
      - ApplicationInsights__InstrumentationKey=5a7144dc-f2eb-4db8-98ed-e1dd497ff712
      - ApplicationInsights__ApplicationName=WebAltasDes
      - ConnectionStrings__BestinverSts=Data Source=bestinver.bbdd;Initial Catalog=STS2;User ID=sa;Password=Kabel.2020;
    ports:
      - "80"
      - "443"
    volumes:
      #- ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
      - ./docker/certificates:C:\https\certs

  bestinver.wordpress.ws:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

